### ISSUE TITLE
打开之后什么都没有 

### ISSUE THREAD

**Issue by 1737587401** [Avenshy/WELearnToSleep#12]

**Comment by Avenshy** [comment]
以管理员权限打开试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Avenshy/WELearnToSleep"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 晚上9:30
收件人:&nbsp;"Avenshy/WELearnToSleep"<WELearnToSleep@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Avenshy/WELearnToSleep] 打开之后什么都没有  (#12)

**Comment by 1737587401** [comment]
> 以管理员权限打开试试
> […](#)
> ------------------＆nbsp;原始邮件＆nbsp; ------------------发件人：“ Avenshy / WELearnToSleep “ <notifications@github.com> ;; 发送时间：＆nbsp; 2020年12月18日（星期五）晚上9:30收件人：“ Avenshy / WELearnToSleep” <WELearnToSleep@noreply.github.com> ;; 抄送：“ Subscribed” <subscribed@noreply.github.com> ;; 主题：＆nbsp; [Avenshy / WELearnToSleep]：之后什么都没有（[＃12](https://github.com/Avenshy/WELearnToSleep/issues/12)）—您收到此消息是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

可以了 谢谢
