### ISSUE TITLE
'{"ret":3002,"mess":"对象不存在！"}'

### ISSUE THREAD

**Issue by mxcoras** [Avenshy/WELearnToSleep#3]
除了setscoinfo和savescoinfo160928外还有没有其他方法

**Comment by Avenshy** [comment]
能否提供账号密码进行测试呢，保证只用于此程序的开发。
Avenshy@qq.com

**Comment by mxcoras** [comment]
你好，我解决了。我待会儿提一个pr，谢谢你的脚本，帮了大忙


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Avenshy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 下午2:09
收件人:&nbsp;"Avenshy/WELearnToSleep"<WELearnToSleep@noreply.github.com&gt;;
抄送:&nbsp;" "<2382413024@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Avenshy/WELearnToSleep] '{"ret":3002,"mess":"对象不存在！"}' (#3)





 
能否提供账号密码进行测试呢，保证只用于此程序的开发。
 Avenshy@qq.com

**Comment by Avenshy** [comment]
好的，辛苦了

**Comment by mxcoras** [comment]
发了pr，merge一下^_^

**Comment by mxcoras** [comment]
fixed
