### ISSUE TITLE
这是什么情况？

### ISSUE THREAD

**Issue by solife2020** [Avenshy/WELearnToSleep#5]
![微信截图_20200501074719](https://user-images.githubusercontent.com/60801692/80769688-9d56af00-8b80-11ea-9f3f-f7f1863ccf0b.png)

**Comment by mxcoras** [comment]
请尝试一下更新后的版本😉

**Comment by solife2020** [comment]
新版的可以刷课了，有答题功能吗

**Comment by Avenshy** [comment]
可以配合显示答案的脚本手动刷课
https://greasyfork.org/zh-CN/scripts?filter_locale=0&q=welearn

**Comment by solife2020** [comment]
![微信截图_20200501172304](https://user-images.githubusercontent.com/60801692/80795909-72944700-8bd0-11ea-9a75-030b3f33d3dd.png)
无学习时长算不算BUG?

**Comment by mxcoras** [comment]
> ![微信截图_20200501172304](https://user-images.githubusercontent.com/60801692/80795909-72944700-8bd0-11ea-9a75-030b3f33d3dd.png)
> 无学习时长算不算BUG?

我试着向服务器发送心跳包，但是学习时长未被记录，之后我有时间会用其他办法试试看能不能做到刷时间

**Comment by solife2020** [comment]
无学习时长容易被被罚。

**Comment by Avenshy** [comment]
学习时长？在做了在做了 （咕咕咕

**Comment by solife2020** [comment]
就需要时长才正常啊

**Comment by Avenshy** [comment]
https://github.com/Avenshy/WELearnToSleeep  刷学习时长来了

**Comment by giwosi** [comment]
各位大佬有没有u校园的
