### ISSUE TITLE
Linux使用python3运行报错

### ISSUE THREAD

**Issue by Makebignew** [Avenshy/WELearnToSleep#8]
错误信息如下：
debian:~# python3  WELearnToSleep.py
  File "WELearnToSleep.py", line 42
    print(f'[NO.{i:>2}] 完成度{course["per"]:>3}% {course["name"]}')

望指点迷津，谢谢。

**Comment by Avenshy** [comment]
这里使用了f-string，需要python3.6及以上版本的支持，升级您的python版本即可解决该问题。  
刚刚在ubuntu上测试没有问题。
![screenshot](https://i.loli.net/2020/06/05/GP25TK1tUeCjzrO.png)

**Comment by Makebignew** [comment]
> 这里使用了f-string，需要python3.6及以上版本的支持，升级您的python版本即可解决该问题。
> 刚刚在ubuntu上测试没有问题。
> ![screenshot](https://camo.githubusercontent.com/1298fef71e2a17262c23749ec6dc4b257a30f748/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30362f30352f47503235544b31745565436a7a724f2e706e67)
非常感谢您的耐心解答。升级python版本后，问题已解决。
